<?php
// Typography
Redux::setSection( $opt_name, array(
	'title'            => esc_html__( 'Typography', 'asata' ),
	'id'               => 'bt_typography',
	'icon'             => 'el el-fontsize',
	'fields'           => array(
		array(
			'id'       => 'body_font',
			'type'     => 'typography',
			'title'    => esc_html__( 'Body Font', 'asata' ),
			'subtitle' => esc_html__( 'These settings control the typography body.', 'asata' ),
			'subsets'   => false,
			'letter-spacing'   => true,
			'text-align'   => false,
			'color'   => false,
			'ext-font-css' => get_template_directory().'/framework/options/fonts.css',
			'fonts'  => $fonts, 'google' => false,
			'default'  => '',
			'output'    => array('body')
		),
		array(
			'id'       => 'h1_font',
			'type'     => 'typography',
			'title'    => esc_html__( 'H1 Typography', 'asata' ),
			'subtitle' => esc_html__( 'These settings control the typography H1.', 'asata' ),
			'subsets'   => false,
			'letter-spacing'   => true,
			'text-align'   => false,
			'color'   => false,
			'ext-font-css' => get_template_directory().'/framework/options/fonts.css',
			'fonts'  => $fonts, 'google' => false,
			'default'  => '',
			'output'    => array('h1, .bt-font-h1')
		),
		array(
			'id'       => 'h2_font',
			'type'     => 'typography',
			'title'    => esc_html__( 'H2 Typography', 'asata' ),
			'subtitle' => esc_html__( 'These settings control the typography H2.', 'asata' ),
			'subsets'   => false,
			'letter-spacing'   => true,
			'text-align'   => false,
			'color'   => false,
			'ext-font-css' => get_template_directory().'/framework/options/fonts.css',
			'fonts'  => $fonts, 'google' => false,
			'default'  => '',
			'output'    => array('h2, .bt-font-h2')
		),
		array(
			'id'       => 'h3_font',
			'type'     => 'typography',
			'title'    => esc_html__( 'H3 Typography', 'asata' ),
			'subtitle' => esc_html__( 'These settings control the typography H3.', 'asata' ),
			'subsets'   => false,
			'letter-spacing'   => true,
			'text-align'   => false,
			'color'   => false,
			'ext-font-css' => get_template_directory().'/framework/options/fonts.css',
			'fonts'  => $fonts, 'google' => false,
			'default'  => '',
			'output'    => array('h3, .bt-font-h3')
		),
		array(
			'id'       => 'h4_font',
			'type'     => 'typography',
			'title'    => esc_html__( 'H4 Typography', 'asata' ),
			'subtitle' => esc_html__( 'These settings control the typography H4.', 'asata' ),
			'subsets'   => false,
			'letter-spacing'   => true,
			'text-align'   => false,
			'color'   => false,
			'ext-font-css' => get_template_directory().'/framework/options/fonts.css',
			'fonts'  => $fonts, 'google' => false,
			'default'  => '',
			'output'    => array('h4, .bt-font-h4')
		),
		array(
			'id'       => 'h5_font',
			'type'     => 'typography',
			'title'    => esc_html__( 'H5 Typography', 'asata' ),
			'subtitle' => esc_html__( 'These settings control the typography H5.', 'asata' ),
			'subsets'   => false,
			'letter-spacing'   => true,
			'text-align'   => false,
			'color'   => false,
			'ext-font-css' => get_template_directory().'/framework/options/fonts.css',
			'fonts'  => $fonts, 'google' => false,
			'default'  => '',
			'output'    => array('h5, .bt-font-h5')
		),
		array(
			'id'       => 'h6_font',
			'type'     => 'typography',
			'title'    => esc_html__( 'H6 Typography', 'asata' ),
			'subtitle' => esc_html__( 'These settings control the typography H6.', 'asata' ),
			'subsets'   => false,
			'letter-spacing'   => true,
			'text-align'   => false,
			'color'   => false,
			'ext-font-css' => get_template_directory().'/framework/options/fonts.css',
			'fonts'  => $fonts, 'google' => false,
			'default'  => '',
			'output'    => array('h6, .bt-font-h6')
		),
		array(
			'id'       => 'button_font',
			'type'     => 'typography',
			'title'    => esc_html__( 'Button Typography', 'asata' ),
			'subtitle' => esc_html__( 'These settings control the typography button.', 'asata' ),
			'subsets'   => false,
			'letter-spacing'   => true,
			'text-align'   => false,
			'color'   => false,
			'ext-font-css' => get_template_directory().'/framework/options/fonts.css',
			'fonts'  => $fonts, 'google' => false,
			'default'  => '',
			'output'    => array('.button, .bt-btn, .vc_btn3')
		),
		
	)
) );
Redux::setSection( $opt_name, array(
	'title'            => esc_html__( 'Extra Font', 'asata' ),
	'id'               => 'bt_extrafont',
	'subsection'       => true,
	'fields'           => array(
		array(
			'id'       => 'extra_font_1',
			'type'     => 'typography',
			'title'    => esc_html__( 'Extra Font 1', 'asata' ),
			'subtitle' => esc_html__( 'Select a font to use throughout Typography settings.', 'asata' ),
			'subsets'   => false,
			'font-size'   => false,
			'font-style'   => false,
			'line-height'   => false,
			'text-align'   => false,
			'color'   => false,
			'ext-font-css' => get_template_directory().'/framework/options/fonts.css',
			'fonts'  => $fonts, 'google' => false,
		),
		array(
			'id'=>'extra_element_1',
			'type' => 'textarea',
			'title' => esc_html__('Elements 1', 'asata'), 
			'subtitle' => esc_html__('Add the html tags, element ID or class as you need. Ex: body,a,.class-name,#tag-id,...', 'asata'),
			'default' => ''
		),
		array(
			'id'       => 'extra_font_2',
			'type'     => 'typography',
			'title'    => esc_html__( 'Extra Font 2', 'asata' ),
			'subtitle' => esc_html__( 'Select a font to use throughout Typography settings.', 'asata' ),
			'subsets'   => false,
			'font-size'   => false,
			'font-style'   => false,
			'line-height'   => false,
			'text-align'   => false,
			'color'   => false,
			'ext-font-css' => get_template_directory().'/framework/options/fonts.css',
			'fonts'  => $fonts, 'google' => false,
		),
		array(
			'id'=>'extra_element_2',
			'type' => 'textarea',
			'title' => esc_html__('Elements 2', 'asata'), 
			'subtitle' => esc_html__('Add the html tags, element ID or class as you need. Ex: body,a,.class-name,#tag-id,...', 'asata'),
			'default' => ''
		),
		array(
			'id'       => 'extra_font_3',
			'type'     => 'typography',
			'title'    => esc_html__( 'Extra Font 3', 'asata' ),
			'subtitle' => esc_html__( 'Select a font to use throughout Typography settings.', 'asata' ),
			'subsets'   => false,
			'font-size'   => false,
			'font-style'   => false,
			'line-height'   => false,
			'text-align'   => false,
			'color'   => false,
			'ext-font-css' => get_template_directory().'/framework/options/fonts.css',
			'fonts'  => $fonts, 'google' => false,
		),
		array(
			'id'=>'extra_element_3',
			'type' => 'textarea',
			'title' => esc_html__('Elements 3', 'asata'), 
			'subtitle' => esc_html__('Add the html tags, element ID or class as you need. Ex: body,a,.class-name,#tag-id,...', 'asata'),
			'default' => ''
		),
	)
) );
